# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
from typing import Any as _Any

from . import a2a_pb2 as a2a__pb2  # type: ignore[possibly-unbound-import]

experimental: _Any = getattr(grpc, "experimental", grpc)

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in a2a_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class A2AServiceStub(object):
    """A2A Protocol Buffer definitions for Bindu gRPC support
    This file defines the gRPC service and message types for Agent-to-Agent communication

    A2A Service - Main service for agent communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
            "/bindu.a2a.v1.A2AService/SendMessage",
            request_serializer=a2a__pb2.MessageSendRequest.SerializeToString,
            response_deserializer=a2a__pb2.MessageSendResponse.FromString,
            _registered_method=True,
        )
        self.StreamMessage = channel.unary_stream(
            "/bindu.a2a.v1.A2AService/StreamMessage",
            request_serializer=a2a__pb2.MessageSendRequest.SerializeToString,
            response_deserializer=a2a__pb2.TaskEvent.FromString,
            _registered_method=True,
        )
        self.GetTask = channel.unary_unary(
            "/bindu.a2a.v1.A2AService/GetTask",
            request_serializer=a2a__pb2.TaskQueryRequest.SerializeToString,
            response_deserializer=a2a__pb2.Task.FromString,
            _registered_method=True,
        )
        self.ListTasks = channel.unary_unary(
            "/bindu.a2a.v1.A2AService/ListTasks",
            request_serializer=a2a__pb2.ListTasksRequest.SerializeToString,
            response_deserializer=a2a__pb2.TaskListResponse.FromString,
            _registered_method=True,
        )
        self.CancelTask = channel.unary_unary(
            "/bindu.a2a.v1.A2AService/CancelTask",
            request_serializer=a2a__pb2.TaskIdRequest.SerializeToString,
            response_deserializer=a2a__pb2.Task.FromString,
            _registered_method=True,
        )
        self.TaskFeedback = channel.unary_unary(
            "/bindu.a2a.v1.A2AService/TaskFeedback",
            request_serializer=a2a__pb2.TaskFeedbackRequest.SerializeToString,
            response_deserializer=a2a__pb2.TaskFeedbackResponse.FromString,
            _registered_method=True,
        )
        self.ListContexts = channel.unary_unary(
            "/bindu.a2a.v1.A2AService/ListContexts",
            request_serializer=a2a__pb2.ListContextsRequest.SerializeToString,
            response_deserializer=a2a__pb2.ContextListResponse.FromString,
            _registered_method=True,
        )
        self.ClearContext = channel.unary_unary(
            "/bindu.a2a.v1.A2AService/ClearContext",
            request_serializer=a2a__pb2.ContextIdRequest.SerializeToString,
            response_deserializer=a2a__pb2.ContextClearResponse.FromString,
            _registered_method=True,
        )
        self.SetTaskPushNotification = channel.unary_unary(
            "/bindu.a2a.v1.A2AService/SetTaskPushNotification",
            request_serializer=a2a__pb2.SetTaskPushNotificationRequest.SerializeToString,
            response_deserializer=a2a__pb2.TaskPushNotificationConfig.FromString,
            _registered_method=True,
        )
        self.GetTaskPushNotification = channel.unary_unary(
            "/bindu.a2a.v1.A2AService/GetTaskPushNotification",
            request_serializer=a2a__pb2.GetTaskPushNotificationRequest.SerializeToString,
            response_deserializer=a2a__pb2.TaskPushNotificationConfig.FromString,
            _registered_method=True,
        )
        self.ListTaskPushNotifications = channel.unary_unary(
            "/bindu.a2a.v1.A2AService/ListTaskPushNotifications",
            request_serializer=a2a__pb2.ListTaskPushNotificationsRequest.SerializeToString,
            response_deserializer=a2a__pb2.TaskPushNotificationListResponse.FromString,
            _registered_method=True,
        )
        self.DeleteTaskPushNotification = channel.unary_unary(
            "/bindu.a2a.v1.A2AService/DeleteTaskPushNotification",
            request_serializer=a2a__pb2.DeleteTaskPushNotificationRequest.SerializeToString,
            response_deserializer=a2a__pb2.DeleteTaskPushNotificationResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/bindu.a2a.v1.A2AService/HealthCheck",
            request_serializer=a2a__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=a2a__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class A2AServiceServicer(object):
    """A2A Protocol Buffer definitions for Bindu gRPC support
    This file defines the gRPC service and message types for Agent-to-Agent communication

    A2A Service - Main service for agent communication
    """

    def SendMessage(self, request, context):
        """Message operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTask(self, request, context):
        """Task operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TaskFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListContexts(self, request, context):
        """Context operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ClearContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetTaskPushNotification(self, request, context):
        """Push notification operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTaskPushNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTaskPushNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteTaskPushNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_A2AServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendMessage": grpc.unary_unary_rpc_method_handler(
            servicer.SendMessage,
            request_deserializer=a2a__pb2.MessageSendRequest.FromString,
            response_serializer=a2a__pb2.MessageSendResponse.SerializeToString,
        ),
        "StreamMessage": grpc.unary_stream_rpc_method_handler(
            servicer.StreamMessage,
            request_deserializer=a2a__pb2.MessageSendRequest.FromString,
            response_serializer=a2a__pb2.TaskEvent.SerializeToString,
        ),
        "GetTask": grpc.unary_unary_rpc_method_handler(
            servicer.GetTask,
            request_deserializer=a2a__pb2.TaskQueryRequest.FromString,
            response_serializer=a2a__pb2.Task.SerializeToString,
        ),
        "ListTasks": grpc.unary_unary_rpc_method_handler(
            servicer.ListTasks,
            request_deserializer=a2a__pb2.ListTasksRequest.FromString,
            response_serializer=a2a__pb2.TaskListResponse.SerializeToString,
        ),
        "CancelTask": grpc.unary_unary_rpc_method_handler(
            servicer.CancelTask,
            request_deserializer=a2a__pb2.TaskIdRequest.FromString,
            response_serializer=a2a__pb2.Task.SerializeToString,
        ),
        "TaskFeedback": grpc.unary_unary_rpc_method_handler(
            servicer.TaskFeedback,
            request_deserializer=a2a__pb2.TaskFeedbackRequest.FromString,
            response_serializer=a2a__pb2.TaskFeedbackResponse.SerializeToString,
        ),
        "ListContexts": grpc.unary_unary_rpc_method_handler(
            servicer.ListContexts,
            request_deserializer=a2a__pb2.ListContextsRequest.FromString,
            response_serializer=a2a__pb2.ContextListResponse.SerializeToString,
        ),
        "ClearContext": grpc.unary_unary_rpc_method_handler(
            servicer.ClearContext,
            request_deserializer=a2a__pb2.ContextIdRequest.FromString,
            response_serializer=a2a__pb2.ContextClearResponse.SerializeToString,
        ),
        "SetTaskPushNotification": grpc.unary_unary_rpc_method_handler(
            servicer.SetTaskPushNotification,
            request_deserializer=a2a__pb2.SetTaskPushNotificationRequest.FromString,
            response_serializer=a2a__pb2.TaskPushNotificationConfig.SerializeToString,
        ),
        "GetTaskPushNotification": grpc.unary_unary_rpc_method_handler(
            servicer.GetTaskPushNotification,
            request_deserializer=a2a__pb2.GetTaskPushNotificationRequest.FromString,
            response_serializer=a2a__pb2.TaskPushNotificationConfig.SerializeToString,
        ),
        "ListTaskPushNotifications": grpc.unary_unary_rpc_method_handler(
            servicer.ListTaskPushNotifications,
            request_deserializer=a2a__pb2.ListTaskPushNotificationsRequest.FromString,
            response_serializer=a2a__pb2.TaskPushNotificationListResponse.SerializeToString,
        ),
        "DeleteTaskPushNotification": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteTaskPushNotification,
            request_deserializer=a2a__pb2.DeleteTaskPushNotificationRequest.FromString,
            response_serializer=a2a__pb2.DeleteTaskPushNotificationResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=a2a__pb2.HealthCheckRequest.FromString,
            response_serializer=a2a__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "bindu.a2a.v1.A2AService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "bindu.a2a.v1.A2AService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class A2AService(object):
    """A2A Protocol Buffer definitions for Bindu gRPC support
    This file defines the gRPC service and message types for Agent-to-Agent communication

    A2A Service - Main service for agent communication
    """

    @staticmethod
    def SendMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_unary(
            request,
            target,
            "/bindu.a2a.v1.A2AService/SendMessage",
            a2a__pb2.MessageSendRequest.SerializeToString,
            a2a__pb2.MessageSendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_stream(
            request,
            target,
            "/bindu.a2a.v1.A2AService/StreamMessage",
            a2a__pb2.MessageSendRequest.SerializeToString,
            a2a__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_unary(
            request,
            target,
            "/bindu.a2a.v1.A2AService/GetTask",
            a2a__pb2.TaskQueryRequest.SerializeToString,
            a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListTasks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_unary(
            request,
            target,
            "/bindu.a2a.v1.A2AService/ListTasks",
            a2a__pb2.ListTasksRequest.SerializeToString,
            a2a__pb2.TaskListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelTask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_unary(
            request,
            target,
            "/bindu.a2a.v1.A2AService/CancelTask",
            a2a__pb2.TaskIdRequest.SerializeToString,
            a2a__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TaskFeedback(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_unary(
            request,
            target,
            "/bindu.a2a.v1.A2AService/TaskFeedback",
            a2a__pb2.TaskFeedbackRequest.SerializeToString,
            a2a__pb2.TaskFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListContexts(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_unary(
            request,
            target,
            "/bindu.a2a.v1.A2AService/ListContexts",
            a2a__pb2.ListContextsRequest.SerializeToString,
            a2a__pb2.ContextListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ClearContext(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_unary(
            request,
            target,
            "/bindu.a2a.v1.A2AService/ClearContext",
            a2a__pb2.ContextIdRequest.SerializeToString,
            a2a__pb2.ContextClearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetTaskPushNotification(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_unary(
            request,
            target,
            "/bindu.a2a.v1.A2AService/SetTaskPushNotification",
            a2a__pb2.SetTaskPushNotificationRequest.SerializeToString,
            a2a__pb2.TaskPushNotificationConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTaskPushNotification(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_unary(
            request,
            target,
            "/bindu.a2a.v1.A2AService/GetTaskPushNotification",
            a2a__pb2.GetTaskPushNotificationRequest.SerializeToString,
            a2a__pb2.TaskPushNotificationConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListTaskPushNotifications(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_unary(
            request,
            target,
            "/bindu.a2a.v1.A2AService/ListTaskPushNotifications",
            a2a__pb2.ListTaskPushNotificationsRequest.SerializeToString,
            a2a__pb2.TaskPushNotificationListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteTaskPushNotification(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_unary(
            request,
            target,
            "/bindu.a2a.v1.A2AService/DeleteTaskPushNotification",
            a2a__pb2.DeleteTaskPushNotificationRequest.SerializeToString,
            a2a__pb2.DeleteTaskPushNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return experimental.unary_unary(
            request,
            target,
            "/bindu.a2a.v1.A2AService/HealthCheck",
            a2a__pb2.HealthCheckRequest.SerializeToString,
            a2a__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
